import {
  AdobeStock,
  Dreamstime,
  Freepik,
  Shutterstock,
  Vecteezy,
} from "@/components/icons";
import { Generator } from "@/types";
import {
  CheckCircle,
  FilePenLine,
  FileVideo,
  PlusCircle,
  Settings
} from "lucide-react";

export const sidebarItems = [
  {
    title: "Create CSV",
    icon: FilePenLine,
    href: "/dashboard",
  },
  {
    title: "Buy Credits",
    icon: PlusCircle,
    href: "/dashboard/credits",
  },
  {
    title: "Tutorials",
    icon: FileVideo,
    href: "/dashboard/tutorials",
    badge: "How to use",
  },
  {
    title: "Settings",
    icon: Settings,
    href: "/dashboard/settings",
  },
];

export const generators: Generator[] = [
  {
    id: 1,
    title: "AdobeStock",
    color: "#FD4949",
    icon: AdobeStock,
    csvRequirements: {
      structure: ["Filename", "Title", "Keywords", "Category"],
      generate: ["Title", "Keywords", "Category"],
      delimiter: ",",
    },
    categories: [
      { id: 1, name: "Animals" },
      { id: 2, name: "Buildings and Architecture" },
      { id: 3, name: "Business" },
      { id: 4, name: "Drinks" },
      { id: 5, name: "The Environment" },
      { id: 6, name: "States of Mind" },
      { id: 7, name: "Food" },
      { id: 8, name: "Graphic Resources" },
      { id: 9, name: "Hobbies and Leisure" },
      { id: 10, name: "Industry" },
      { id: 11, name: "Landscape" },
      { id: 12, name: "Lifestyle" },
      { id: 13, name: "People" },
      { id: 14, name: "Plants and Flowers" },
      { id: 15, name: "Culture and Religion" },
      { id: 16, name: "Science" },
      { id: 17, name: "Social Issues" },
      { id: 18, name: "Sports" },
      { id: 19, name: "Technology" },
      { id: 20, name: "Transport" },
      { id: 21, name: "Travel" },
    ],
    comingSoon: false,
  },
  {
    id: 2,
    title: "Shutterstock",
    color: "#FDB549",
    icon: Shutterstock,
    csvRequirements: {
      structure: ["Filename", "Description", "Keywords", "Categories"],
      generate: ["Description", "Keywords", "Categories"],
      delimiter: ",",
    },
    categories: [
      { id: 1, name: "Abstract" },
      { id: 2, name: "Animals/Wildlife" },
      { id: 3, name: "Arts" },
      { id: 4, name: "Backgrounds/Textures" },
      { id: 5, name: "Beauty/Fashion" },
      { id: 6, name: "Buildings/Landmarks" },
      { id: 7, name: "Business/Finance" },
      { id: 8, name: "Celebrities" },
      { id: 9, name: "Education" },
      { id: 10, name: "Food and Drink" },
      { id: 11, name: "Healthcare/Medical" },
      { id: 12, name: "Holidays" },
      { id: 13, name: "Industrial" },
      { id: 14, name: "Interiors" },
      { id: 15, name: "Miscellaneous" },
      { id: 16, name: "Nature" },
      { id: 17, name: "Objects" },
      { id: 18, name: "Parks/Outdoor" },
      { id: 19, name: "People" },
      { id: 20, name: "Religion" },
      { id: 21, name: "Science" },
      { id: 22, name: "Signs/Symbols" },
      { id: 23, name: "Sports/Recreation" },
      { id: 24, name: "Technology" },
      { id: 25, name: "Transportation" },
      { id: 26, name: "Vintage" },
    ],
    comingSoon: false,
  },
  {
    id: 3,
    title: "Freepik",
    color: "#83FD49",
    icon: Freepik,
    csvRequirements: {
      structure: ["File name", "Title", "Keywords", "Prompt", "Model"],
      generate: ["Title", "Keywords"],
      delimiter: ";",
    },
    models: [
      "Adobe Firefly",
      "Dall-e 1",
      "Dall-e 2",
      "Dall-e 3",
      "Freepik Pikaso",
      "Ideogram 1.0",
      "Leonardo",
      "Midjourney 1",
      "Midjourney 2",
      "Midjourney 3",
      "Midjourney 4",
      "Midjourney 5",
      "Midjourney 5.1",
      "Midjourney 5.2",
      "Midjourney 6",
      "Stable Diffusion 1.4",
      "Stable Diffusion 1.5",
      "Stable Diffusion 2.0",
      "Stable Diffusion 2.1",
      "Stable Diffusion XL",
      "Wepik",
    ],
    comingSoon: false,
  },
  {
    id: 4,
    title: "Vecteezy",
    color: "#49fddd",
    icon: Vecteezy,
    csvRequirements: {
      structure: ["Filename", "Title", "Description", "Keywords"],
      generate: ["Title", "Description", "Keywords"],
      delimiter: ",",
    },
    comingSoon: false,
  },
  // {
  //   id: 8,
  //   title: "MiriCanvas",
  //   color: "#DD4FC3",
  //   icon: Dreamstime,
  //   csvRequirements: {
  //     structure: [
  //       "Filename",
  //       "Image Name",
  //       "Description",
  //       "Category 1",
  //       "Category 2",
  //       "Category 3",
  //       "Keywords",
  //     ],
  //     generate: ["Image Name", "Description", "keywords"],
  //     delimiter: ",",
  //   },
  //   comingSoon: true,
  // },
];

export const allowedFileTypes = [
  {
    id: 1,
    title: "JPG",
    type: "image/jpeg",
    color: "#00d8d6",
  },
  {
    id: 2,
    title: "PNG",
    type: "image/png",
    color: "#7d5fff",
  },
];
